# xpix 配置文件示例
# 复制此文件到 ~/.config/xpix/config.toml 使用

[watermark]
# 注意: 字体文件固定为 ~/Library/Fonts/CaskaydiaMonoNerdFont-Regular.ttf
# 请将字体文件放置到该位置

# 字体大小（相对于图像宽度的比例）
# 例如：0.033 表示字体大小为图像宽度的 3.3%
font_size = 0.033

# 水印位置
# 可选值: "top-left", "top-center", "top-right", "bottom-left", "bottom-center", "bottom-right", "center"
position = "bottom-center"

# 水印透明度 (0.0 - 1.0)
opacity = 0.7

# 水印颜色 (十六进制格式)
# 白色: "#FFFFFF"
# 黑色: "#000000"
# 灰色: "#808080"
color = "#FFFFFF"

# 水印边距（像素）
margin = 20

[output]
# JPEG 输出质量 (1-100)
# 推荐值: 90-95
quality = 95

# 输出格式
# 可选值: "auto" (根据输入格式自动选择), "jpeg", "png"
format = "auto"

